rm(list=ls())
data<-read.csv("C:/Users/BREB/OneDrive/Documents/MSc Thesis/Thesis/PIDDataset/Inlier_Samples.csv")

library(caTools)
set.seed(123)
split=sample.split(data$class,SplitRatio =0.8)
training=subset(data,split==TRUE)
testing=subset(data,split==FALSE)
write.csv(training,"C:/Users/BREB/OneDrive/Documents/MSc Thesis/Thesis/PIDDataset/Diabetes_Dataset_Outlier_Removed_Train80p.csv")
write.csv(testing,"C:/Users/BREB/OneDrive/Documents/MSc Thesis/Thesis/PIDDataset/Diabetes_Dataset_Test20p.csv")
